apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: postgres
    appMajor: "12"
    instance: dspace.postgres.lib.unb.ca
    tier: database
    uri: dspace.postgres.lib.unb.ca
    vcsOwner: unb-libraries
    vcsRepository: dspace.postgres.lib.unb.ca
    vcsRef: prod
  name: dspace-postgres-lib-unb-ca
  namespace: prod
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        appMajor: "12"
        instance: dspace.postgres.lib.unb.ca
        tier: database
        uri: dspace.postgres.lib.unb.ca
        vcsOwner: unb-libraries
        vcsRepository: dspace.postgres.lib.unb.ca
        vcsRef: prod
    spec:
      containers:
        -
          env:
            -
              name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: root-password
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          name: dspace-postgres-lib-unb-ca
          ports:
            -
              containerPort: 5432
              name: postgres
          volumeMounts:
            -
              mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
      priorityClassName: vip-essential
      imagePullSecrets:
        -
          name: docker-hub-auth
      restartPolicy: Always
      volumes:
        -
          name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: dspace-postgres-lib-unb-ca
